# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\POO\PROYECTOS\Proyectoe\Ui\Menu\u_mesa5.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(784, 669)
        self.cuenta5 = QtWidgets.QTableWidget(Dialog)
        self.cuenta5.setGeometry(QtCore.QRect(370, 10, 401, 531))
        self.cuenta5.setObjectName("cuenta5")
        self.cuenta5.setColumnCount(3)
        self.cuenta5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.cuenta5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cuenta5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cuenta5.setHorizontalHeaderItem(2, item)
        self.cuenta5.horizontalHeader().setMinimumSectionSize(40)
        self.cuenta5.verticalHeader().setMinimumSectionSize(40)
        self.total5 = QtWidgets.QLabel(Dialog)
        self.total5.setGeometry(QtCore.QRect(630, 550, 91, 16))
        self.total5.setObjectName("total5")
        self.arroz5 = QtWidgets.QPushButton(Dialog)
        self.arroz5.setGeometry(QtCore.QRect(50, 60, 131, 61))
        self.arroz5.setObjectName("arroz5")
        self.pera5 = QtWidgets.QPushButton(Dialog)
        self.pera5.setGeometry(QtCore.QRect(200, 60, 131, 61))
        self.pera5.setObjectName("pera5")
        self.hamburguesa5 = QtWidgets.QPushButton(Dialog)
        self.hamburguesa5.setGeometry(QtCore.QRect(50, 140, 131, 61))
        self.hamburguesa5.setObjectName("hamburguesa5")
        self.pizza5 = QtWidgets.QPushButton(Dialog)
        self.pizza5.setGeometry(QtCore.QRect(200, 140, 131, 61))
        self.pizza5.setObjectName("pizza5")
        self.borrar5 = QtWidgets.QPushButton(Dialog)
        self.borrar5.setGeometry(QtCore.QRect(380, 550, 93, 28))
        self.borrar5.setObjectName("borrar5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.cuenta5.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Producto"))
        item = self.cuenta5.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Cantidad"))
        item = self.cuenta5.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Precio"))
        self.total5.setText(_translate("Dialog", "TOTAL"))
        self.arroz5.setText(_translate("Dialog", "ARROZ"))
        self.pera5.setText(_translate("Dialog", "PERA"))
        self.hamburguesa5.setText(_translate("Dialog", "HAMBURGUESA"))
        self.pizza5.setText(_translate("Dialog", "PIZZA"))
        self.borrar5.setText(_translate("Dialog", "BORRAR FILA"))
