# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\POO\PROYECTOS\Proyectoe\Ui\Menu\u_mesa3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(784, 669)
        self.cuenta3 = QtWidgets.QTableWidget(Dialog)
        self.cuenta3.setGeometry(QtCore.QRect(370, 10, 401, 531))
        self.cuenta3.setObjectName("cuenta3")
        self.cuenta3.setColumnCount(3)
        self.cuenta3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.cuenta3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cuenta3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cuenta3.setHorizontalHeaderItem(2, item)
        self.cuenta3.horizontalHeader().setMinimumSectionSize(40)
        self.cuenta3.verticalHeader().setMinimumSectionSize(40)
        self.total3 = QtWidgets.QLabel(Dialog)
        self.total3.setGeometry(QtCore.QRect(630, 550, 91, 16))
        self.total3.setObjectName("total3")
        self.arroz3 = QtWidgets.QPushButton(Dialog)
        self.arroz3.setGeometry(QtCore.QRect(50, 60, 131, 61))
        self.arroz3.setObjectName("arroz3")
        self.pera3 = QtWidgets.QPushButton(Dialog)
        self.pera3.setGeometry(QtCore.QRect(200, 60, 131, 61))
        self.pera3.setObjectName("pera3")
        self.hamburguesa3 = QtWidgets.QPushButton(Dialog)
        self.hamburguesa3.setGeometry(QtCore.QRect(50, 140, 131, 61))
        self.hamburguesa3.setObjectName("hamburguesa3")
        self.pizza3 = QtWidgets.QPushButton(Dialog)
        self.pizza3.setGeometry(QtCore.QRect(200, 140, 131, 61))
        self.pizza3.setObjectName("pizza3")
        self.borrar3 = QtWidgets.QPushButton(Dialog)
        self.borrar3.setGeometry(QtCore.QRect(380, 550, 93, 28))
        self.borrar3.setObjectName("borrar3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.cuenta3.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Producto"))
        item = self.cuenta3.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Cantidad"))
        item = self.cuenta3.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Precio"))
        self.total3.setText(_translate("Dialog", "TOTAL"))
        self.arroz3.setText(_translate("Dialog", "ARROZ"))
        self.pera3.setText(_translate("Dialog", "PERA"))
        self.hamburguesa3.setText(_translate("Dialog", "HAMBURGUESA"))
        self.pizza3.setText(_translate("Dialog", "PIZZA"))
        self.borrar3.setText(_translate("Dialog", "BORRAR FILA"))
