# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\POO\PROYECTOS\Proyectoe\Ui\Menu\u_mesa6.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(784, 669)
        self.cuenta6 = QtWidgets.QTableWidget(Dialog)
        self.cuenta6.setGeometry(QtCore.QRect(370, 10, 401, 531))
        self.cuenta6.setObjectName("cuenta6")
        self.cuenta6.setColumnCount(3)
        self.cuenta6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.cuenta6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cuenta6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cuenta6.setHorizontalHeaderItem(2, item)
        self.cuenta6.horizontalHeader().setMinimumSectionSize(40)
        self.cuenta6.verticalHeader().setMinimumSectionSize(40)
        self.total6 = QtWidgets.QLabel(Dialog)
        self.total6.setGeometry(QtCore.QRect(630, 550, 91, 16))
        self.total6.setObjectName("total6")
        self.arroz6 = QtWidgets.QPushButton(Dialog)
        self.arroz6.setGeometry(QtCore.QRect(50, 60, 131, 61))
        self.arroz6.setObjectName("arroz6")
        self.pera6 = QtWidgets.QPushButton(Dialog)
        self.pera6.setGeometry(QtCore.QRect(200, 60, 131, 61))
        self.pera6.setObjectName("pera6")
        self.hamburguesa6 = QtWidgets.QPushButton(Dialog)
        self.hamburguesa6.setGeometry(QtCore.QRect(50, 140, 131, 61))
        self.hamburguesa6.setObjectName("hamburguesa6")
        self.pizza6 = QtWidgets.QPushButton(Dialog)
        self.pizza6.setGeometry(QtCore.QRect(200, 140, 131, 61))
        self.pizza6.setObjectName("pizza6")
        self.borrar6 = QtWidgets.QPushButton(Dialog)
        self.borrar6.setGeometry(QtCore.QRect(380, 550, 93, 28))
        self.borrar6.setObjectName("borrar6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.cuenta6.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Producto"))
        item = self.cuenta6.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Cantidad"))
        item = self.cuenta6.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Precio"))
        self.total6.setText(_translate("Dialog", "TOTAL"))
        self.arroz6.setText(_translate("Dialog", "ARROZ"))
        self.pera6.setText(_translate("Dialog", "PERA"))
        self.hamburguesa6.setText(_translate("Dialog", "HAMBURGUESA"))
        self.pizza6.setText(_translate("Dialog", "PIZZA"))
        self.borrar6.setText(_translate("Dialog", "BORRAR FILA"))
