# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\POO\PROYECTOS\Proyectoe\Ui\Menu\u_mesa2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(784, 669)
        self.cuenta2 = QtWidgets.QTableWidget(Dialog)
        self.cuenta2.setGeometry(QtCore.QRect(370, 10, 401, 531))
        self.cuenta2.setObjectName("cuenta2")
        self.cuenta2.setColumnCount(3)
        self.cuenta2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.cuenta2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cuenta2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cuenta2.setHorizontalHeaderItem(2, item)
        self.cuenta2.horizontalHeader().setMinimumSectionSize(40)
        self.cuenta2.verticalHeader().setMinimumSectionSize(40)
        self.total2 = QtWidgets.QLabel(Dialog)
        self.total2.setGeometry(QtCore.QRect(630, 550, 91, 16))
        self.total2.setObjectName("total2")
        self.arroz2 = QtWidgets.QPushButton(Dialog)
        self.arroz2.setGeometry(QtCore.QRect(50, 60, 131, 61))
        self.arroz2.setObjectName("arroz2")
        self.pera2 = QtWidgets.QPushButton(Dialog)
        self.pera2.setGeometry(QtCore.QRect(200, 60, 131, 61))
        self.pera2.setObjectName("pera2")
        self.hamburguesa2 = QtWidgets.QPushButton(Dialog)
        self.hamburguesa2.setGeometry(QtCore.QRect(50, 140, 131, 61))
        self.hamburguesa2.setObjectName("hamburguesa2")
        self.pizza2 = QtWidgets.QPushButton(Dialog)
        self.pizza2.setGeometry(QtCore.QRect(200, 140, 131, 61))
        self.pizza2.setObjectName("pizza2")
        self.borrar2 = QtWidgets.QPushButton(Dialog)
        self.borrar2.setGeometry(QtCore.QRect(380, 550, 93, 28))
        self.borrar2.setObjectName("borrar2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.cuenta2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Producto"))
        item = self.cuenta2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Cantidad"))
        item = self.cuenta2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Precio"))
        self.total2.setText(_translate("Dialog", "TOTAL"))
        self.arroz2.setText(_translate("Dialog", "ARROZ"))
        self.pera2.setText(_translate("Dialog", "PERA"))
        self.hamburguesa2.setText(_translate("Dialog", "HAMBURGUESA"))
        self.pizza2.setText(_translate("Dialog", "PIZZA"))
        self.borrar2.setText(_translate("Dialog", "BORRAR FILA"))
