# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\POO\PROYECTOS\Proyectoe\Ui\Recepcion\u_recepcion.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1091, 501)
        Dialog.setMinimumSize(QtCore.QSize(1091, 501))
        Dialog.setMaximumSize(QtCore.QSize(1091, 501))
        Dialog.setStyleSheet("")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.menu = QtWidgets.QWidget(Dialog)
        self.menu.setMinimumSize(QtCore.QSize(111, 501))
        self.menu.setMaximumSize(QtCore.QSize(111, 501))
        self.menu.setStyleSheet("background-color: #f5f5f5")
        self.menu.setObjectName("menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout_3.setContentsMargins(-1, 10, -1, 15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.menu)
        self.label.setMinimumSize(QtCore.QSize(71, 31))
        self.label.setMaximumSize(QtCore.QSize(71, 31))
        self.label.setStyleSheet("background-color: #f5f5f5;\n"
"border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        spacerItem2 = QtWidgets.QSpacerItem(25, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.widget_2 = QtWidgets.QWidget(self.menu)
        self.widget_2.setMinimumSize(QtCore.QSize(71, 41))
        self.widget_2.setMaximumSize(QtCore.QSize(71, 41))
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 71, 31))
        self.label_3.setStyleSheet("background-color: #6cc644;\n"
"border: 1px solid #f5f5f5;\n"
"border-radius: 10px;\n"
"padding: 10px 20px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: #333333;\n"
"border: 1px solid;\n"
"border-radius: 10px;\n"
"color: rgb(245, 245, 245)")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setIndent(-1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.widget_2)
        spacerItem4 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        spacerItem5 = QtWidgets.QSpacerItem(25, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem6 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.widget_4 = QtWidgets.QWidget(self.menu)
        self.widget_4.setMinimumSize(QtCore.QSize(71, 41))
        self.widget_4.setMaximumSize(QtCore.QSize(71, 41))
        self.widget_4.setObjectName("widget_4")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 71, 31))
        self.label_4.setStyleSheet("background-color: #f6c40f;\n"
"border: 1px solid #f5f5f5;\n"
"border-radius: 10px;\n"
"padding: 10px 20px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.widget_4)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: #333333;\n"
"border: 1px solid;\n"
"border-radius: 10px;\n"
"color: rgb(245, 245, 245)")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setIndent(-1)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.widget_4)
        spacerItem7 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        spacerItem8 = QtWidgets.QSpacerItem(25, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem9 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.widget_5 = QtWidgets.QWidget(self.menu)
        self.widget_5.setMinimumSize(QtCore.QSize(71, 41))
        self.widget_5.setMaximumSize(QtCore.QSize(71, 41))
        self.widget_5.setObjectName("widget_5")
        self.label_7 = QtWidgets.QLabel(self.widget_5)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: #333333;\n"
"border: 1px solid;\n"
"border-radius: 10px;\n"
"color: rgb(245, 245, 245)")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setIndent(-1)
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.widget_5)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 71, 31))
        self.label_5.setStyleSheet("background-color: #bd2c00;\n"
"border: 1px solid #f5f5f5;\n"
"border-radius: 10px;\n"
"padding: 10px 20px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_5.raise_()
        self.label_7.raise_()
        self.horizontalLayout_9.addWidget(self.widget_5)
        spacerItem10 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        spacerItem11 = QtWidgets.QSpacerItem(25, 77, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem11)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem12 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.pushButton = QtWidgets.QPushButton(self.menu)
        self.pushButton.setMinimumSize(QtCore.QSize(71, 51))
        self.pushButton.setStyleSheet("QPushButton {background-color: #333333;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        color: rgb(245, 245, 245)\n"
"    }\n"
"    QPushButton:hover {background-color: #2a2a2a;\n"
"    }\n"
"    QPushButton:pressed {background-color: #2a2a2a;\n"
"    }")
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_11.addWidget(self.pushButton)
        spacerItem13 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        spacerItem14 = QtWidgets.QSpacerItem(25, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem14)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem15 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem15)
        self.b_salir_1 = QtWidgets.QPushButton(self.menu)
        self.b_salir_1.setMinimumSize(QtCore.QSize(71, 24))
        self.b_salir_1.setStyleSheet("QPushButton {background-color: #333333;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        color: rgb(245, 245, 245)\n"
"    }\n"
"    QPushButton:hover {background-color: #2a2a2a;\n"
"    }\n"
"    QPushButton:pressed {background-color: #2a2a2a;\n"
"    }")
        self.b_salir_1.setObjectName("b_salir_1")
        self.horizontalLayout_12.addWidget(self.b_salir_1)
        spacerItem16 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem16)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13.addWidget(self.menu)
        self.Reservaciones = QtWidgets.QWidget(Dialog)
        self.Reservaciones.setMinimumSize(QtCore.QSize(271, 501))
        self.Reservaciones.setMaximumSize(QtCore.QSize(271, 501))
        self.Reservaciones.setStyleSheet("background-color: #333333;\n"
"border-color: #f5f5f5;\n"
"")
        self.Reservaciones.setObjectName("Reservaciones")
        self.tableWidget = QtWidgets.QTableWidget(self.Reservaciones)
        self.tableWidget.setGeometry(QtCore.QRect(10, 80, 251, 301))
        self.tableWidget.setStyleSheet("background-color: #f5f5f5;\n"
"border: 1px solid #333333")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.layoutWidget_2 = QtWidgets.QWidget(self.Reservaciones)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 420, 271, 26))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem17 = QtWidgets.QSpacerItem(131, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem17)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_4.setMinimumSize(QtCore.QSize(131, 24))
        self.pushButton_4.setMaximumSize(QtCore.QSize(131, 24))
        self.pushButton_4.setStyleSheet("QPushButton {background-color: #f5f5f5;\n"
"        border: 1px solid #333333;\n"
"        border-radius: 10px;\n"
"        color: #333333\n"
"    }\n"
"    QPushButton:hover {background-color: #eaeaea;\n"
"    }\n"
"    QPushButton:pressed {background-color: #eaeaea;\n"
"    }")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        spacerItem18 = QtWidgets.QSpacerItem(131, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem18)
        self.layoutWidget = QtWidgets.QWidget(self.Reservaciones)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 460, 271, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem19 = QtWidgets.QSpacerItem(131, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem19)
        self.b_salir_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.b_salir_2.setMinimumSize(QtCore.QSize(131, 24))
        self.b_salir_2.setMaximumSize(QtCore.QSize(131, 24))
        self.b_salir_2.setStyleSheet("QPushButton {background-color: #f5f5f5;\n"
"        border: 1px solid #333333;\n"
"        border-radius: 10px;\n"
"        color: #333333\n"
"    }\n"
"    QPushButton:hover {background-color: #eaeaea;\n"
"    }\n"
"    QPushButton:pressed {background-color: #eaeaea;\n"
"    }")
        self.b_salir_2.setObjectName("b_salir_2")
        self.horizontalLayout_3.addWidget(self.b_salir_2)
        spacerItem20 = QtWidgets.QSpacerItem(131, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem20)
        self.layoutWidget1 = QtWidgets.QWidget(self.Reservaciones)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 10, 271, 33))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem21)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setMinimumSize(QtCore.QSize(131, 31))
        self.label_11.setMaximumSize(QtCore.QSize(131, 31))
        self.label_11.setStyleSheet("background-color: #f5f5f5;\n"
"border: 1px solid;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem22)
        self.horizontalLayout_13.addWidget(self.Reservaciones)
        self.content = QtWidgets.QWidget(Dialog)
        self.content.setMinimumSize(QtCore.QSize(801, 501))
        self.content.setMaximumSize(QtCore.QSize(1001, 501))
        self.content.setStyleSheet("border-left: 1px solid #f5f5f5;\n"
"background-color: #333333;")
        self.content.setObjectName("content")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.content)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem23 = QtWidgets.QSpacerItem(38, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem23)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.content)
        self.label_2.setMinimumSize(QtCore.QSize(101, 31))
        self.label_2.setStyleSheet("background-color: #f5f5f5;\n"
"border-left: 1px solid;\n"
"border-top: 1px solid;\n"
"border-bottom: 1px solid;\n"
"border-right: 0;\n"
"\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"\n"
"color: #333333")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_9 = QtWidgets.QLabel(self.content)
        self.label_9.setMinimumSize(QtCore.QSize(431, 31))
        self.label_9.setStyleSheet("background-color: #f5f5f5;\n"
"border-right: 1px solid;\n"
"border-top: 1px solid;\n"
"border-bottom: 1px solid;\n"
"border-left: 0px;\n"
"\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"\n"
"color: #333333")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem24 = QtWidgets.QSpacerItem(78, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem24)
        self.label_10 = QtWidgets.QLabel(self.content)
        self.label_10.setMinimumSize(QtCore.QSize(181, 31))
        self.label_10.setStyleSheet("background-color: #f5f5f5;\n"
"border-radius: 10px;\n"
"border: 1px solid;\n"
"color: #333333")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        spacerItem25 = QtWidgets.QSpacerItem(38, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem25)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem26 = QtWidgets.QSpacerItem(17, 75, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem26)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem27 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem27)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem28, 0, 7, 1, 1)
        self.m_4 = QtWidgets.QPushButton(self.content)
        self.m_4.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_4.setFont(font)
        self.m_4.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_4.setObjectName("m_4")
        self.gridLayout.addWidget(self.m_4, 0, 6, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem29, 0, 9, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem30, 0, 11, 1, 1)
        self.m_2 = QtWidgets.QPushButton(self.content)
        self.m_2.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_2.setFont(font)
        self.m_2.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_2.setObjectName("m_2")
        self.gridLayout.addWidget(self.m_2, 0, 2, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem31, 0, 1, 1, 1)
        self.m_3 = QtWidgets.QPushButton(self.content)
        self.m_3.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_3.setFont(font)
        self.m_3.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_3.setObjectName("m_3")
        self.gridLayout.addWidget(self.m_3, 0, 4, 1, 1)
        self.m_1 = QtWidgets.QPushButton(self.content)
        self.m_1.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_1.setFont(font)
        self.m_1.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_1.setCheckable(True)
        self.m_1.setObjectName("m_1")
        self.gridLayout.addWidget(self.m_1, 0, 0, 1, 1)
        self.m_6 = QtWidgets.QPushButton(self.content)
        self.m_6.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_6.setFont(font)
        self.m_6.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_6.setObjectName("m_6")
        self.gridLayout.addWidget(self.m_6, 0, 10, 1, 1)
        self.m_7 = QtWidgets.QPushButton(self.content)
        self.m_7.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_7.setFont(font)
        self.m_7.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_7.setObjectName("m_7")
        self.gridLayout.addWidget(self.m_7, 0, 12, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem32, 0, 3, 1, 1)
        self.m_5 = QtWidgets.QPushButton(self.content)
        self.m_5.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_5.setFont(font)
        self.m_5.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_5.setObjectName("m_5")
        self.gridLayout.addWidget(self.m_5, 0, 8, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem33, 0, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem34)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.m_8 = QtWidgets.QPushButton(self.content)
        self.m_8.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_8.setFont(font)
        self.m_8.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_8.setObjectName("m_8")
        self.gridLayout_2.addWidget(self.m_8, 0, 0, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem35, 0, 1, 1, 1)
        self.m_12 = QtWidgets.QPushButton(self.content)
        self.m_12.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_12.setFont(font)
        self.m_12.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_12.setObjectName("m_12")
        self.gridLayout_2.addWidget(self.m_12, 0, 8, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem36, 0, 9, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem37, 0, 7, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem38, 0, 3, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem39, 0, 5, 1, 1)
        self.m_11 = QtWidgets.QPushButton(self.content)
        self.m_11.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_11.setFont(font)
        self.m_11.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_11.setObjectName("m_11")
        self.gridLayout_2.addWidget(self.m_11, 0, 6, 1, 1)
        self.m_10 = QtWidgets.QPushButton(self.content)
        self.m_10.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_10.setFont(font)
        self.m_10.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_10.setObjectName("m_10")
        self.gridLayout_2.addWidget(self.m_10, 0, 4, 1, 1)
        self.m_9 = QtWidgets.QPushButton(self.content)
        self.m_9.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_9.setFont(font)
        self.m_9.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_9.setObjectName("m_9")
        self.gridLayout_2.addWidget(self.m_9, 0, 2, 1, 1)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem40, 0, 11, 1, 1)
        self.m_13 = QtWidgets.QPushButton(self.content)
        self.m_13.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_13.setFont(font)
        self.m_13.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_13.setObjectName("m_13")
        self.gridLayout_2.addWidget(self.m_13, 0, 10, 1, 1)
        self.m_14 = QtWidgets.QPushButton(self.content)
        self.m_14.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_14.setFont(font)
        self.m_14.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_14.setObjectName("m_14")
        self.gridLayout_2.addWidget(self.m_14, 0, 12, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem41 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem41)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.m_19 = QtWidgets.QPushButton(self.content)
        self.m_19.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_19.setFont(font)
        self.m_19.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_19.setObjectName("m_19")
        self.gridLayout_3.addWidget(self.m_19, 0, 9, 1, 1)
        self.m_15 = QtWidgets.QPushButton(self.content)
        self.m_15.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_15.setFont(font)
        self.m_15.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_15.setObjectName("m_15")
        self.gridLayout_3.addWidget(self.m_15, 0, 0, 1, 1)
        self.m_20 = QtWidgets.QPushButton(self.content)
        self.m_20.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_20.setFont(font)
        self.m_20.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_20.setObjectName("m_20")
        self.gridLayout_3.addWidget(self.m_20, 0, 11, 1, 1)
        self.m_18 = QtWidgets.QPushButton(self.content)
        self.m_18.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_18.setFont(font)
        self.m_18.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_18.setObjectName("m_18")
        self.gridLayout_3.addWidget(self.m_18, 0, 7, 1, 1)
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem42, 0, 8, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem43, 0, 1, 1, 1)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem44, 0, 4, 1, 1)
        self.m_16 = QtWidgets.QPushButton(self.content)
        self.m_16.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_16.setFont(font)
        self.m_16.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_16.setObjectName("m_16")
        self.gridLayout_3.addWidget(self.m_16, 0, 3, 1, 1)
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem45, 0, 6, 1, 1)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem46, 0, 12, 1, 1)
        self.m_17 = QtWidgets.QPushButton(self.content)
        self.m_17.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_17.setFont(font)
        self.m_17.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_17.setObjectName("m_17")
        self.gridLayout_3.addWidget(self.m_17, 0, 5, 1, 1)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem47, 0, 10, 1, 1)
        self.m_21 = QtWidgets.QPushButton(self.content)
        self.m_21.setMinimumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.m_21.setFont(font)
        self.m_21.setStyleSheet("QPushButton {background-color: #6cc644;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {background-color: #5eaa3b;\n"
"    }\n"
"    QPushButton:pressed {background-color: #589f37;\n"
"    }")
        self.m_21.setObjectName("m_21")
        self.gridLayout_3.addWidget(self.m_21, 0, 13, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        spacerItem48 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem48)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem49 = QtWidgets.QSpacerItem(17, 74, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem49)
        self.horizontalLayout_13.addWidget(self.content)

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(self.Reservaciones.show) # type: ignore
        self.pushButton_4.clicked.connect(self.menu.show) # type: ignore
        self.pushButton_4.clicked.connect(self.Reservaciones.hide) # type: ignore
        self.pushButton.clicked.connect(self.menu.hide) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Menu"))
        self.label_6.setText(_translate("Dialog", "Disp."))
        self.label_8.setText(_translate("Dialog", "Resv."))
        self.label_7.setText(_translate("Dialog", "Ocu."))
        self.pushButton.setText(_translate("Dialog", "Resv."))
        self.b_salir_1.setText(_translate("Dialog", "Salir"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Cantidad"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Fecha"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Hora"))
        self.pushButton_4.setText(_translate("Dialog", "Cerrar"))
        self.b_salir_2.setText(_translate("Dialog", "Salir"))
        self.label_11.setText(_translate("Dialog", "Reservaciones"))
        self.label_2.setText(_translate("Dialog", "Encargado:"))
        self.label_9.setText(_translate("Dialog", "Nombre del encargado"))
        self.label_10.setText(_translate("Dialog", "Receción"))
        self.m_4.setText(_translate("Dialog", "4"))
        self.m_2.setText(_translate("Dialog", "2"))
        self.m_3.setText(_translate("Dialog", "3"))
        self.m_1.setText(_translate("Dialog", "1"))
        self.m_6.setText(_translate("Dialog", "6"))
        self.m_7.setText(_translate("Dialog", "7"))
        self.m_5.setText(_translate("Dialog", "5"))
        self.m_8.setText(_translate("Dialog", "8"))
        self.m_12.setText(_translate("Dialog", "12"))
        self.m_11.setText(_translate("Dialog", "11"))
        self.m_10.setText(_translate("Dialog", "10"))
        self.m_9.setText(_translate("Dialog", "9"))
        self.m_13.setText(_translate("Dialog", "13"))
        self.m_14.setText(_translate("Dialog", "14"))
        self.m_19.setText(_translate("Dialog", "19"))
        self.m_15.setText(_translate("Dialog", "15"))
        self.m_20.setText(_translate("Dialog", "20"))
        self.m_18.setText(_translate("Dialog", "18"))
        self.m_16.setText(_translate("Dialog", "16"))
        self.m_17.setText(_translate("Dialog", "17"))
        self.m_21.setText(_translate("Dialog", "21"))
