# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\POO\PROYECTOS\Proyectoe\Ui\Almacen\u_agregar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(332, 395)
        Dialog.setStyleSheet("background-color: rgb(51, 51, 51);")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(140, 220, 111, 22))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"    color: black; /* Asegura que el texto sea visible */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #f5f5f5;\n"
"    color: black; /* Color del texto en el menú desplegable */\n"
"}\n"
"QComboBox::item:selected {\n"
"    background-color: #dcdcdc; /* Fondo del texto seleccionado */\n"
"    color: black; /* Color del texto seleccionado */\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.linecantidad = QtWidgets.QLineEdit(Dialog)
        self.linecantidad.setGeometry(QtCore.QRect(140, 100, 113, 22))
        self.linecantidad.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.linecantidad.setObjectName("linecantidad")
        self.titulo_bodega_2 = QtWidgets.QLabel(Dialog)
        self.titulo_bodega_2.setGeometry(QtCore.QRect(30, 30, 281, 24))
        self.titulo_bodega_2.setStyleSheet("QLabel {\n"
"    font: 63 italic 10pt \"Sitka Small Semibold\";\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.titulo_bodega_2.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_bodega_2.setObjectName("titulo_bodega_2")
        self.productoproveedor = QtWidgets.QLabel(Dialog)
        self.productoproveedor.setGeometry(QtCore.QRect(40, 160, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.productoproveedor.setFont(font)
        self.productoproveedor.setStyleSheet("QLabel {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.productoproveedor.setObjectName("productoproveedor")
        self.Productoprecio_4 = QtWidgets.QLabel(Dialog)
        self.Productoprecio_4.setGeometry(QtCore.QRect(40, 70, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.Productoprecio_4.setFont(font)
        self.Productoprecio_4.setStyleSheet("QLabel {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.Productoprecio_4.setObjectName("Productoprecio_4")
        self.lineprecio = QtWidgets.QLineEdit(Dialog)
        self.lineprecio.setGeometry(QtCore.QRect(140, 190, 113, 22))
        self.lineprecio.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.lineprecio.setObjectName("lineprecio")
        self.Productoprecio_3 = QtWidgets.QLabel(Dialog)
        self.Productoprecio_3.setGeometry(QtCore.QRect(40, 100, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.Productoprecio_3.setFont(font)
        self.Productoprecio_3.setStyleSheet("QLabel {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.Productoprecio_3.setObjectName("Productoprecio_3")
        self.Productoprecio_2 = QtWidgets.QLabel(Dialog)
        self.Productoprecio_2.setGeometry(QtCore.QRect(40, 220, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.Productoprecio_2.setFont(font)
        self.Productoprecio_2.setStyleSheet("QLabel {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.Productoprecio_2.setObjectName("Productoprecio_2")
        self.lineproveedor = QtWidgets.QLineEdit(Dialog)
        self.lineproveedor.setGeometry(QtCore.QRect(140, 160, 113, 22))
        self.lineproveedor.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.lineproveedor.setObjectName("lineproveedor")
        self.Productoprecio = QtWidgets.QLabel(Dialog)
        self.Productoprecio.setGeometry(QtCore.QRect(40, 190, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.Productoprecio.setFont(font)
        self.Productoprecio.setStyleSheet("QLabel {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.Productoprecio.setObjectName("Productoprecio")
        self.productoproveedor_2 = QtWidgets.QLabel(Dialog)
        self.productoproveedor_2.setGeometry(QtCore.QRect(40, 130, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.productoproveedor_2.setFont(font)
        self.productoproveedor_2.setStyleSheet("QLabel {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.productoproveedor_2.setObjectName("productoproveedor_2")
        self.linecodigo = QtWidgets.QLineEdit(Dialog)
        self.linecodigo.setGeometry(QtCore.QRect(140, 130, 113, 22))
        self.linecodigo.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.linecodigo.setObjectName("linecodigo")
        self.linenombre = QtWidgets.QLineEdit(Dialog)
        self.linenombre.setGeometry(QtCore.QRect(140, 70, 111, 21))
        self.linenombre.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.linenombre.setText("")
        self.linenombre.setObjectName("linenombre")
        self.agregar = QtWidgets.QPushButton(Dialog)
        self.agregar.setGeometry(QtCore.QRect(200, 340, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.agregar.setFont(font)
        self.agregar.setStyleSheet("QPushButton {\n"
"        background-color: #f5f5f5;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"")
        self.agregar.setObjectName("agregar")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 331, 391))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_8.raise_()
        self.comboBox.raise_()
        self.linecantidad.raise_()
        self.titulo_bodega_2.raise_()
        self.productoproveedor.raise_()
        self.Productoprecio_4.raise_()
        self.lineprecio.raise_()
        self.Productoprecio_3.raise_()
        self.Productoprecio_2.raise_()
        self.lineproveedor.raise_()
        self.Productoprecio.raise_()
        self.productoproveedor_2.raise_()
        self.linecodigo.raise_()
        self.linenombre.raise_()
        self.agregar.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.comboBox.setItemText(0, _translate("Dialog", "Bebidas"))
        self.comboBox.setItemText(1, _translate("Dialog", "Bebidas A."))
        self.comboBox.setItemText(2, _translate("Dialog", "Carnes"))
        self.comboBox.setItemText(3, _translate("Dialog", "Condimentos"))
        self.comboBox.setItemText(4, _translate("Dialog", "Frutas y Verduras"))
        self.comboBox.setItemText(5, _translate("Dialog", "Panadería"))
        self.comboBox.setItemText(6, _translate("Dialog", "Lácteos"))
        self.titulo_bodega_2.setText(_translate("Dialog", "Ingresar producto"))
        self.productoproveedor.setText(_translate("Dialog", "Proveedor"))
        self.Productoprecio_4.setText(_translate("Dialog", "Nombre"))
        self.Productoprecio_3.setText(_translate("Dialog", "Cantidad"))
        self.Productoprecio_2.setText(_translate("Dialog", "Tipo"))
        self.Productoprecio.setText(_translate("Dialog", "Precio"))
        self.productoproveedor_2.setText(_translate("Dialog", "Código"))
        self.agregar.setText(_translate("Dialog", "Agregar "))
