# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\POO\PROYECTOS\Proyectoe\Ui\Almacen\u_almacen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1131, 646)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        Form.setFont(font)
        Form.setStyleSheet("background-color: rgb(51, 51, 51);")
        self.barrabusqueda = QtWidgets.QLineEdit(Form)
        self.barrabusqueda.setGeometry(QtCore.QRect(120, 70, 341, 21))
        self.barrabusqueda.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(245, 245, 245);\n"
"}\n"
"")
        self.barrabusqueda.setText("")
        self.barrabusqueda.setObjectName("barrabusqueda")
        self.lbl_busqueda = QtWidgets.QLabel(Form)
        self.lbl_busqueda.setGeometry(QtCore.QRect(20, 70, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(12)
        self.lbl_busqueda.setFont(font)
        self.lbl_busqueda.setStyleSheet("color: #4078c0")
        self.lbl_busqueda.setObjectName("lbl_busqueda")
        self.ENCARGADO = QtWidgets.QLabel(Form)
        self.ENCARGADO.setGeometry(QtCore.QRect(20, 30, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(12)
        self.ENCARGADO.setFont(font)
        self.ENCARGADO.setStyleSheet("color: #4078c0")
        self.ENCARGADO.setObjectName("ENCARGADO")
        self.titulo_bodega = QtWidgets.QLabel(Form)
        self.titulo_bodega.setGeometry(QtCore.QRect(0, 0, 721, 24))
        font = QtGui.QFont()
        font.setFamily("Sitka Small Semibold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.titulo_bodega.setFont(font)
        self.titulo_bodega.setStyleSheet("\n"
"color: #4078c0")
        self.titulo_bodega.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_bodega.setObjectName("titulo_bodega")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 110, 741, 521))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTableWidget {\n"
"    background-color: #f5f5f5; /* Set entire widget background to #f5f5f5 */\n"
"    border: none; /* Remove external border */\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    gridline-color: #ddd; /* Keep gridlines for column distinction */\n"
"}\n"
"QTableWidget::item {\n"
"    background-color: #f5f5f5; /* Set item background to #f5f5f5 */\n"
"    border: none; /* Remove item border */\n"
"    padding: 5px;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #f5f5f5; /* Set header background to #f5f5f5 */\n"
"    border: 1px solid #ccc; /* Keep header border for distinction */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"QTabWidget {\n"
"    background-color: #f5f5f5; /* Set tab widget background to #f5f5f5 */\n"
"    border: none; /* Remove external border */\n"
"    border-radius: 10px;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.BEBIDAS = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BEBIDAS.setFont(font)
        self.BEBIDAS.setObjectName("BEBIDAS")
        self.tabla_producto = QtWidgets.QTableWidget(self.BEBIDAS)
        self.tabla_producto.setGeometry(QtCore.QRect(10, 10, 721, 481))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(9)
        self.tabla_producto.setFont(font)
        self.tabla_producto.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.tabla_producto.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_producto.setObjectName("tabla_producto")
        self.tabla_producto.setColumnCount(6)
        self.tabla_producto.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto.setHorizontalHeaderItem(5, item)
        self.label = QtWidgets.QLabel(self.BEBIDAS)
        self.label.setGeometry(QtCore.QRect(0, 0, 741, 501))
        self.label.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.tabla_producto.raise_()
        self.tabWidget.addTab(self.BEBIDAS, "")
        self.BEBIDASA = QtWidgets.QWidget()
        self.BEBIDASA.setObjectName("BEBIDASA")
        self.tabla_producto_2 = QtWidgets.QTableWidget(self.BEBIDASA)
        self.tabla_producto_2.setGeometry(QtCore.QRect(10, 10, 711, 481))
        self.tabla_producto_2.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.tabla_producto_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_producto_2.setObjectName("tabla_producto_2")
        self.tabla_producto_2.setColumnCount(6)
        self.tabla_producto_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_2.setHorizontalHeaderItem(5, item)
        self.label_2 = QtWidgets.QLabel(self.BEBIDASA)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 741, 501))
        self.label_2.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.tabla_producto_2.raise_()
        self.tabWidget.addTab(self.BEBIDASA, "")
        self.CARNES = QtWidgets.QWidget()
        self.CARNES.setObjectName("CARNES")
        self.tabla_producto_3 = QtWidgets.QTableWidget(self.CARNES)
        self.tabla_producto_3.setGeometry(QtCore.QRect(10, 10, 711, 481))
        self.tabla_producto_3.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.tabla_producto_3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_producto_3.setObjectName("tabla_producto_3")
        self.tabla_producto_3.setColumnCount(6)
        self.tabla_producto_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_3.setHorizontalHeaderItem(5, item)
        self.label_3 = QtWidgets.QLabel(self.CARNES)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 741, 501))
        self.label_3.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.tabla_producto_3.raise_()
        self.tabWidget.addTab(self.CARNES, "")
        self.POSTRES = QtWidgets.QWidget()
        self.POSTRES.setObjectName("POSTRES")
        self.tabla_producto_4 = QtWidgets.QTableWidget(self.POSTRES)
        self.tabla_producto_4.setGeometry(QtCore.QRect(10, 10, 711, 481))
        self.tabla_producto_4.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.tabla_producto_4.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_producto_4.setObjectName("tabla_producto_4")
        self.tabla_producto_4.setColumnCount(6)
        self.tabla_producto_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_4.setHorizontalHeaderItem(5, item)
        self.label_4 = QtWidgets.QLabel(self.POSTRES)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 741, 501))
        self.label_4.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.tabla_producto_4.raise_()
        self.tabWidget.addTab(self.POSTRES, "")
        self.ENTRADAS = QtWidgets.QWidget()
        self.ENTRADAS.setObjectName("ENTRADAS")
        self.tabla_producto_5 = QtWidgets.QTableWidget(self.ENTRADAS)
        self.tabla_producto_5.setGeometry(QtCore.QRect(10, 10, 711, 481))
        self.tabla_producto_5.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.tabla_producto_5.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_producto_5.setObjectName("tabla_producto_5")
        self.tabla_producto_5.setColumnCount(6)
        self.tabla_producto_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_5.setHorizontalHeaderItem(5, item)
        self.label_5 = QtWidgets.QLabel(self.ENTRADAS)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 741, 501))
        self.label_5.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_5.raise_()
        self.tabla_producto_5.raise_()
        self.tabWidget.addTab(self.ENTRADAS, "")
        self.botonbuscar = QtWidgets.QPushButton(Form)
        self.botonbuscar.setGeometry(QtCore.QRect(470, 60, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.botonbuscar.setFont(font)
        self.botonbuscar.setStyleSheet("QPushButton {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.botonbuscar.setObjectName("botonbuscar")
        self.botonreset = QtWidgets.QPushButton(Form)
        self.botonreset.setGeometry(QtCore.QRect(580, 60, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.botonreset.setFont(font)
        self.botonreset.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.botonreset.setObjectName("botonreset")
        self.editar = QtWidgets.QPushButton(Form)
        self.editar.setGeometry(QtCore.QRect(800, 290, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editar.setFont(font)
        self.editar.setStyleSheet("QPushButton {\n"
"        background-color: #f5f5f5;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"")
        self.editar.setObjectName("editar")
        self.agregar = QtWidgets.QPushButton(Form)
        self.agregar.setGeometry(QtCore.QRect(950, 300, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.agregar.setFont(font)
        self.agregar.setStyleSheet("QPushButton {\n"
"        background-color: #f5f5f5;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"")
        self.agregar.setObjectName("agregar")
        self.Registro = QtWidgets.QPushButton(Form)
        self.Registro.setGeometry(QtCore.QRect(810, 380, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Registro.setFont(font)
        self.Registro.setStyleSheet("QPushButton {\n"
"        background-color: #f5f5f5;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"")
        self.Registro.setObjectName("Registro")
        self.Productoprecio_4 = QtWidgets.QLabel(Form)
        self.Productoprecio_4.setGeometry(QtCore.QRect(850, 110, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.Productoprecio_4.setFont(font)
        self.Productoprecio_4.setStyleSheet("QLabel {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.Productoprecio_4.setObjectName("Productoprecio_4")
        self.titulo_bodega_2 = QtWidgets.QLabel(Form)
        self.titulo_bodega_2.setGeometry(QtCore.QRect(840, 70, 281, 24))
        self.titulo_bodega_2.setStyleSheet("QLabel {\n"
"    font: 63 italic 10pt \"Sitka Small Semibold\";\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.titulo_bodega_2.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_bodega_2.setObjectName("titulo_bodega_2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(950, 260, 111, 22))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"    color: black; /* Asegura que el texto sea visible */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #f5f5f5;\n"
"    color: black; /* Color del texto en el menú desplegable */\n"
"}\n"
"QComboBox::item:selected {\n"
"    background-color: #dcdcdc; /* Fondo del texto seleccionado */\n"
"    color: black; /* Color del texto seleccionado */\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.linecodigo = QtWidgets.QLineEdit(Form)
        self.linecodigo.setGeometry(QtCore.QRect(950, 170, 113, 22))
        self.linecodigo.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.linecodigo.setObjectName("linecodigo")
        self.lineproveedor = QtWidgets.QLineEdit(Form)
        self.lineproveedor.setGeometry(QtCore.QRect(950, 200, 113, 22))
        self.lineproveedor.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.lineproveedor.setObjectName("lineproveedor")
        self.linenombre = QtWidgets.QLineEdit(Form)
        self.linenombre.setGeometry(QtCore.QRect(950, 110, 111, 21))
        self.linenombre.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.linenombre.setText("")
        self.linenombre.setObjectName("linenombre")
        self.linecantidad = QtWidgets.QLineEdit(Form)
        self.linecantidad.setGeometry(QtCore.QRect(950, 140, 113, 22))
        self.linecantidad.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.linecantidad.setObjectName("linecantidad")
        self.productoproveedor = QtWidgets.QLabel(Form)
        self.productoproveedor.setGeometry(QtCore.QRect(850, 200, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.productoproveedor.setFont(font)
        self.productoproveedor.setStyleSheet("QLabel {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.productoproveedor.setObjectName("productoproveedor")
        self.Productoprecio_2 = QtWidgets.QLabel(Form)
        self.Productoprecio_2.setGeometry(QtCore.QRect(850, 260, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.Productoprecio_2.setFont(font)
        self.Productoprecio_2.setStyleSheet("QLabel {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.Productoprecio_2.setObjectName("Productoprecio_2")
        self.lineprecio = QtWidgets.QLineEdit(Form)
        self.lineprecio.setGeometry(QtCore.QRect(950, 230, 113, 22))
        self.lineprecio.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.lineprecio.setObjectName("lineprecio")
        self.Productoprecio_3 = QtWidgets.QLabel(Form)
        self.Productoprecio_3.setGeometry(QtCore.QRect(850, 140, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.Productoprecio_3.setFont(font)
        self.Productoprecio_3.setStyleSheet("QLabel {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.Productoprecio_3.setObjectName("Productoprecio_3")
        self.Productoprecio = QtWidgets.QLabel(Form)
        self.Productoprecio.setGeometry(QtCore.QRect(850, 230, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.Productoprecio.setFont(font)
        self.Productoprecio.setStyleSheet("QLabel {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.Productoprecio.setObjectName("Productoprecio")
        self.productoproveedor_2 = QtWidgets.QLabel(Form)
        self.productoproveedor_2.setGeometry(QtCore.QRect(850, 170, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.productoproveedor_2.setFont(font)
        self.productoproveedor_2.setStyleSheet("QLabel {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.productoproveedor_2.setObjectName("productoproveedor_2")
        self.tabWidget.raise_()
        self.barrabusqueda.raise_()
        self.lbl_busqueda.raise_()
        self.ENCARGADO.raise_()
        self.titulo_bodega.raise_()
        self.botonbuscar.raise_()
        self.botonreset.raise_()
        self.editar.raise_()
        self.agregar.raise_()
        self.Registro.raise_()
        self.Productoprecio_4.raise_()
        self.titulo_bodega_2.raise_()
        self.comboBox.raise_()
        self.linecodigo.raise_()
        self.lineproveedor.raise_()
        self.linenombre.raise_()
        self.linecantidad.raise_()
        self.productoproveedor.raise_()
        self.Productoprecio_2.raise_()
        self.lineprecio.raise_()
        self.Productoprecio_3.raise_()
        self.Productoprecio.raise_()
        self.productoproveedor_2.raise_()

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_busqueda.setText(_translate("Form", "Búsqueda"))
        self.ENCARGADO.setText(_translate("Form", "Encargado:  *******"))
        self.titulo_bodega.setText(_translate("Form", "BODEGA"))
        item = self.tabla_producto.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Código"))
        item = self.tabla_producto.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Precio"))
        item = self.tabla_producto.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Producto"))
        item = self.tabla_producto.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Cantidad"))
        item = self.tabla_producto.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Último Ingreso"))
        item = self.tabla_producto.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Proveedor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BEBIDAS), _translate("Form", "Bebidas"))
        item = self.tabla_producto_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Código"))
        item = self.tabla_producto_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Precio"))
        item = self.tabla_producto_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Producto"))
        item = self.tabla_producto_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Cantidad"))
        item = self.tabla_producto_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Último Ingreso"))
        item = self.tabla_producto_2.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Proveedor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BEBIDASA), _translate("Form", "Bebidas A."))
        item = self.tabla_producto_3.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Código"))
        item = self.tabla_producto_3.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Precio"))
        item = self.tabla_producto_3.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Producto"))
        item = self.tabla_producto_3.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Cantidad"))
        item = self.tabla_producto_3.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Último Ingreso"))
        item = self.tabla_producto_3.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Proveedor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CARNES), _translate("Form", "Carnes"))
        item = self.tabla_producto_4.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Código"))
        item = self.tabla_producto_4.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Precio"))
        item = self.tabla_producto_4.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Producto"))
        item = self.tabla_producto_4.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Cantidad"))
        item = self.tabla_producto_4.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Último Ingreso"))
        item = self.tabla_producto_4.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Proveedor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.POSTRES), _translate("Form", "Postres"))
        item = self.tabla_producto_5.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Código"))
        item = self.tabla_producto_5.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Precio"))
        item = self.tabla_producto_5.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Producto"))
        item = self.tabla_producto_5.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Cantidad"))
        item = self.tabla_producto_5.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Último Ingreso"))
        item = self.tabla_producto_5.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Proveedor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ENTRADAS), _translate("Form", "Entradas"))
        self.botonbuscar.setText(_translate("Form", "Buscar"))
        self.botonreset.setText(_translate("Form", "Reiniciar"))
        self.editar.setText(_translate("Form", "Editar"))
        self.agregar.setText(_translate("Form", "Agregar "))
        self.Registro.setText(_translate("Form", "Registro"))
        self.Productoprecio_4.setText(_translate("Form", "Nombre"))
        self.titulo_bodega_2.setText(_translate("Form", "Ingresar producto"))
        self.comboBox.setItemText(0, _translate("Form", "Bebidas"))
        self.comboBox.setItemText(1, _translate("Form", "Bebidas A."))
        self.comboBox.setItemText(2, _translate("Form", "Carnes"))
        self.comboBox.setItemText(3, _translate("Form", "Postres"))
        self.comboBox.setItemText(4, _translate("Form", "Entradas"))
        self.productoproveedor.setText(_translate("Form", "Proveedor"))
        self.Productoprecio_2.setText(_translate("Form", "Tipo"))
        self.Productoprecio_3.setText(_translate("Form", "Cantidad"))
        self.Productoprecio.setText(_translate("Form", "Precio"))
        self.productoproveedor_2.setText(_translate("Form", "Código"))
