# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\POO\PROYECTOS\Proyectoe\Ui\Almacen\u_editar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(822, 361)
        Dialog.setStyleSheet("background-color: rgb(55, 55, 55);")
        self.productoproveedor_2 = QtWidgets.QLabel(Dialog)
        self.productoproveedor_2.setGeometry(QtCore.QRect(30, 20, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.productoproveedor_2.setFont(font)
        self.productoproveedor_2.setStyleSheet("QLabel {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.productoproveedor_2.setObjectName("productoproveedor_2")
        self.linecodigo = QtWidgets.QLineEdit(Dialog)
        self.linecodigo.setGeometry(QtCore.QRect(130, 20, 113, 22))
        self.linecodigo.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.linecodigo.setObjectName("linecodigo")
        self.buscarcode = QtWidgets.QPushButton(Dialog)
        self.buscarcode.setGeometry(QtCore.QRect(260, 20, 93, 28))
        self.buscarcode.setStyleSheet("QPushButton {\n"
"        background-color: #f5f5f5;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"    }\n"
"")
        self.buscarcode.setObjectName("buscarcode")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(380, 20, 421, 321))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.productoproveedor_2.setText(_translate("Dialog", "Código"))
        self.buscarcode.setText(_translate("Dialog", "Buscar"))
