# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\POO\PROYECTOS\Proyectoe\Ui\Almacen\u_eliminar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(371, 300)
        self.productoproveedor_2 = QtWidgets.QLabel(Dialog)
        self.productoproveedor_2.setGeometry(QtCore.QRect(40, 20, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(9)
        self.productoproveedor_2.setFont(font)
        self.productoproveedor_2.setStyleSheet("QLabel {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.productoproveedor_2.setObjectName("productoproveedor_2")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(30, 60, 331, 141))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.buscarcode2 = QtWidgets.QPushButton(Dialog)
        self.buscarcode2.setGeometry(QtCore.QRect(270, 20, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(9)
        self.buscarcode2.setFont(font)
        self.buscarcode2.setStyleSheet("QPushButton {\n"
"        background-color: #f5f5f5;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"    }\n"
"")
        self.buscarcode2.setObjectName("buscarcode2")
        self.linecodigo4 = QtWidgets.QLineEdit(Dialog)
        self.linecodigo4.setGeometry(QtCore.QRect(140, 20, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(9)
        self.linecodigo4.setFont(font)
        self.linecodigo4.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.linecodigo4.setObjectName("linecodigo4")
        self.eliminar = QtWidgets.QPushButton(Dialog)
        self.eliminar.setGeometry(QtCore.QRect(130, 230, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(10)
        self.eliminar.setFont(font)
        self.eliminar.setStyleSheet("QPushButton {\n"
"        background-color: #f5f5f5;\n"
"        border: 1px solid #f5f5f5;\n"
"        border-radius: 10px;\n"
"\n"
"    }\n"
"")
        self.eliminar.setObjectName("eliminar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.productoproveedor_2.setText(_translate("Dialog", "Código"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Código"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Precio"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Producto"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Cantidad"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Último Ingreso"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Proveedor"))
        self.buscarcode2.setText(_translate("Dialog", "Buscar"))
        self.eliminar.setText(_translate("Dialog", "Eliminar"))
