# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\POO\PROYECTOS\Proyectoe\Ui\MENU DE MESAS\u_mesa4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(784, 669)
        self.cuenta4 = QtWidgets.QTableWidget(Dialog)
        self.cuenta4.setGeometry(QtCore.QRect(370, 10, 401, 531))
        self.cuenta4.setObjectName("cuenta4")
        self.cuenta4.setColumnCount(3)
        self.cuenta4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.cuenta4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cuenta4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cuenta4.setHorizontalHeaderItem(2, item)
        self.cuenta4.horizontalHeader().setMinimumSectionSize(40)
        self.cuenta4.verticalHeader().setMinimumSectionSize(40)
        self.total4 = QtWidgets.QLabel(Dialog)
        self.total4.setGeometry(QtCore.QRect(630, 550, 91, 16))
        self.total4.setObjectName("total4")
        self.arroz4 = QtWidgets.QPushButton(Dialog)
        self.arroz4.setGeometry(QtCore.QRect(50, 60, 131, 61))
        self.arroz4.setObjectName("arroz4")
        self.pera4 = QtWidgets.QPushButton(Dialog)
        self.pera4.setGeometry(QtCore.QRect(200, 60, 131, 61))
        self.pera4.setObjectName("pera4")
        self.hamburguesa4 = QtWidgets.QPushButton(Dialog)
        self.hamburguesa4.setGeometry(QtCore.QRect(50, 140, 131, 61))
        self.hamburguesa4.setObjectName("hamburguesa4")
        self.pizza4 = QtWidgets.QPushButton(Dialog)
        self.pizza4.setGeometry(QtCore.QRect(200, 140, 131, 61))
        self.pizza4.setObjectName("pizza4")
        self.borrar4 = QtWidgets.QPushButton(Dialog)
        self.borrar4.setGeometry(QtCore.QRect(380, 550, 93, 28))
        self.borrar4.setObjectName("borrar4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.cuenta4.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Producto"))
        item = self.cuenta4.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Cantidad"))
        item = self.cuenta4.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Precio"))
        self.total4.setText(_translate("Dialog", "TOTAL"))
        self.arroz4.setText(_translate("Dialog", "ARROZ"))
        self.pera4.setText(_translate("Dialog", "PERA"))
        self.hamburguesa4.setText(_translate("Dialog", "HAMBURGUESA"))
        self.pizza4.setText(_translate("Dialog", "PIZZA"))
        self.borrar4.setText(_translate("Dialog", "BORRAR FILA"))
