# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\POO\PROYECTOS\Proyectoe\Ui\Login\u_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 500)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setStyleSheet("background-color:rgb(54, 54, 54)")
        self.fondogris = QtWidgets.QWidget(Dialog)
        self.fondogris.setGeometry(QtCore.QRect(0, 0, 401, 501))
        self.fondogris.setStyleSheet("\n"
"background-color: rgb(80, 255, 176);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.fondogris.setObjectName("fondogris")
        self.Title = QtWidgets.QLabel(self.fondogris)
        self.Title.setGeometry(QtCore.QRect(0, 50, 400, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(20)
        self.Title.setFont(font)
        self.Title.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.Title.setTextFormat(QtCore.Qt.AutoText)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setWordWrap(False)
        self.Title.setObjectName("Title")
        self.id_emp = QtWidgets.QLineEdit(self.fondogris)
        self.id_emp.setGeometry(QtCore.QRect(140, 150, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(13)
        self.id_emp.setFont(font)
        self.id_emp.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border: 2px solid rgb(122, 143, 168);\n"
"padding: 5px;")
        self.id_emp.setText("")
        self.id_emp.setFrame(True)
        self.id_emp.setObjectName("id_emp")
        self.label = QtWidgets.QLabel(self.fondogris)
        self.label.setGeometry(QtCore.QRect(10, 150, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border: 2px Solid rgb(122, 143, 168);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.fondogris)
        self.label_2.setGeometry(QtCore.QRect(10, 210, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border: 2px Solid rgb(122, 143, 168);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pwd_emp = QtWidgets.QLineEdit(self.fondogris)
        self.pwd_emp.setGeometry(QtCore.QRect(140, 210, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(13)
        self.pwd_emp.setFont(font)
        self.pwd_emp.setStyleSheet("background-color:rgba(255, 255, 255);\n"
"border: 2px solid rgb(122, 143, 168);\n"
"padding: 5px;")
        self.pwd_emp.setText("")
        self.pwd_emp.setFrame(True)
        self.pwd_emp.setObjectName("pwd_emp")
        self.pushlogin = QtWidgets.QPushButton(self.fondogris)
        self.pushlogin.setGeometry(QtCore.QRect(284, 270, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(13)
        self.pushlogin.setFont(font)
        self.pushlogin.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(122, 143, 168);")
        self.pushlogin.setObjectName("pushlogin")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Title.setText(_translate("Dialog", "𝐿𝒪𝒢𝐼𝒩"))
        self.label.setText(_translate("Dialog", "𝐼𝒟 𝐸𝑀𝒫"))
        self.label_2.setText(_translate("Dialog", "𝒫𝒶𝓈𝓈𝓌𝑜𝓇𝒹"))
        self.pushlogin.setText(_translate("Dialog", "𝐿𝒪𝒢𝐼𝒩"))
import fr_rc
