# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\POO\PROYECTOS\Proyectoe\Ui\Login\u_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(401, 501)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setStyleSheet("background-color: rgb(51, 51, 51);")
        self.fondogris = QtWidgets.QWidget(Dialog)
        self.fondogris.setGeometry(QtCore.QRect(0, 0, 401, 501))
        self.fondogris.setStyleSheet("")
        self.fondogris.setObjectName("fondogris")
        self.Title = QtWidgets.QLabel(self.fondogris)
        self.Title.setGeometry(QtCore.QRect(0, 50, 400, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(20)
        self.Title.setFont(font)
        self.Title.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.Title.setTextFormat(QtCore.Qt.AutoText)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setWordWrap(False)
        self.Title.setObjectName("Title")
        self.id_emp = QtWidgets.QLineEdit(self.fondogris)
        self.id_emp.setGeometry(QtCore.QRect(140, 150, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(13)
        self.id_emp.setFont(font)
        self.id_emp.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.id_emp.setText("")
        self.id_emp.setFrame(True)
        self.id_emp.setObjectName("id_emp")
        self.label = QtWidgets.QLabel(self.fondogris)
        self.label.setGeometry(QtCore.QRect(10, 150, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("background-color: #f5f5f5;\n"
"border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.fondogris)
        self.label_2.setGeometry(QtCore.QRect(10, 210, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("background-color: #f5f5f5;\n"
"border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pwd_emp = QtWidgets.QLineEdit(self.fondogris)
        self.pwd_emp.setGeometry(QtCore.QRect(140, 210, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(13)
        self.pwd_emp.setFont(font)
        self.pwd_emp.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #f5f5f5;\n"
"    border-radius: 10px;\n"
"}")
        self.pwd_emp.setText("")
        self.pwd_emp.setFrame(True)
        self.pwd_emp.setObjectName("pwd_emp")
        self.pushlogin = QtWidgets.QPushButton(self.fondogris)
        self.pushlogin.setGeometry(QtCore.QRect(284, 270, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(13)
        self.pushlogin.setFont(font)
        self.pushlogin.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border: 1px solid;\n"
"border-radius: 10px;\n"
"")
        self.pushlogin.setObjectName("pushlogin")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Title.setText(_translate("Dialog", "LOGIN"))
        self.label.setText(_translate("Dialog", "ID EMP"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.pushlogin.setText(_translate("Dialog", "𝐿𝒪𝒢𝐼𝒩"))
