# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\POO\PROYECTOS\Proyectoe\Ui\Login\u_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1091, 501)
        Dialog.setStyleSheet("\n"
"     background: QLinearGradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #1a1a1a, stop: 1 #4a4a4a);\n"
"   ")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1091, 501))
        self.widget.setObjectName("widget")
        self.mainContainer = QtWidgets.QWidget(self.widget)
        self.mainContainer.setGeometry(QtCore.QRect(380, 20, 341, 461))
        self.mainContainer.setMinimumSize(QtCore.QSize(341, 461))
        self.mainContainer.setMaximumSize(QtCore.QSize(341, 461))
        self.mainContainer.setStyleSheet("\n"
"     background: rgba(40, 40, 40, 0.9);\n"
"     border-radius: 20px;\n"
"     border: 2px solid #5d432c;\n"
"    ")
        self.mainContainer.setObjectName("mainContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleLabel = QtWidgets.QLabel(self.mainContainer)
        self.titleLabel.setMinimumSize(QtCore.QSize(341, 61))
        self.titleLabel.setMaximumSize(QtCore.QSize(341, 61))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("\n"
"      color: #c7a17a;\n"
"      background: transparent;\n"
"      qproperty-alignment: AlignCenter;\n"
"      text-shadow: 0 0 10px #c7a17a;\n"
"     ")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.widget_2 = QtWidgets.QWidget(self.mainContainer)
        self.widget_2.setMinimumSize(QtCore.QSize(281, 101))
        self.widget_2.setMaximumSize(QtCore.QSize(281, 1000))
        self.widget_2.setStyleSheet("border: 0px;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.id_emp = QtWidgets.QLineEdit(self.widget_2)
        self.id_emp.setMinimumSize(QtCore.QSize(281, 41))
        self.id_emp.setMaximumSize(QtCore.QSize(281, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.id_emp.setFont(font)
        self.id_emp.setStyleSheet("QLineEdit {\n"
"       background: #2a2a2a;\n"
"       border: 2px solid #5d432c;\n"
"       border-radius: 10px;\n"
"       color: #c7a17a;\n"
"      }\n"
"      QLineEdit:focus {\n"
"       border-color: #c7a17a;\n"
"      }\n"
"     ")
        self.id_emp.setObjectName("id_emp")
        self.verticalLayout.addWidget(self.id_emp)
        spacerItem2 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pwd_emp = QtWidgets.QLineEdit(self.widget_2)
        self.pwd_emp.setMinimumSize(QtCore.QSize(281, 41))
        self.pwd_emp.setMaximumSize(QtCore.QSize(281, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.pwd_emp.setFont(font)
        self.pwd_emp.setStyleSheet("QLineEdit {\n"
"       background: #2a2a2a;\n"
"       border: 2px solid #5d432c;\n"
"       border-radius: 10px;\n"
"       color: #c7a17a;\n"
"      }\n"
"      QLineEdit:focus {\n"
"       border-color: #c7a17a;\n"
"      }\n"
"     ")
        self.pwd_emp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd_emp.setObjectName("pwd_emp")
        self.verticalLayout.addWidget(self.pwd_emp)
        spacerItem3 = QtWidgets.QSpacerItem(20, 61, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.b_login = QtWidgets.QPushButton(self.widget_2)
        self.b_login.setMinimumSize(QtCore.QSize(221, 31))
        self.b_login.setMaximumSize(QtCore.QSize(221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b_login.setFont(font)
        self.b_login.setStyleSheet("QPushButton {\n"
"       background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"         stop:0 #5d432c, stop:1 #c7a17a);\n"
"       color: white;\n"
"       border-radius: 10px;\n"
"       border: none;\n"
"      }\n"
"      QPushButton:hover {\n"
"       background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"         stop:0 #c7a17a, stop:1 #5d432c);\n"
"      }\n"
"      QPushButton:pressed {\n"
"      }\n"
"     ")
        self.b_login.setObjectName("b_login")
        self.horizontalLayout_2.addWidget(self.b_login)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.widget_2)
        spacerItem6 = QtWidgets.QSpacerItem(32, 205, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 55, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.footerText = QtWidgets.QLabel(self.mainContainer)
        self.footerText.setMinimumSize(QtCore.QSize(361, 31))
        self.footerText.setMaximumSize(QtCore.QSize(361, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setItalic(True)
        self.footerText.setFont(font)
        self.footerText.setStyleSheet("\n"
"      color: #c7a17a;\n"
"      background: transparent;\n"
"      qproperty-alignment: AlignCenter;\n"
"     ")
        self.footerText.setObjectName("footerText")
        self.verticalLayout_2.addWidget(self.footerText)
        spacerItem8 = QtWidgets.QSpacerItem(20, 54, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Life: A New Brew"))
        self.titleLabel.setText(_translate("Dialog", "MgtFood"))
        self.id_emp.setPlaceholderText(_translate("Dialog", "Usuario"))
        self.pwd_emp.setPlaceholderText(_translate("Dialog", "Contraseña"))
        self.b_login.setText(_translate("Dialog", "Iniciar Sesión"))
        self.footerText.setText(_translate("Dialog", "MgtFood - 2025"))
