# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\POO\PROYECTOS\Proyectoe\Ui\Meseros\pedidos5.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 1068)
        MainWindow.setStyleSheet("background-color: #C0C0C0;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font-size: 16pt; font-weight: bold; color: #333;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.mesaLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.mesaLineEdit.setStyleSheet("font-size: 16pt; padding: 5px; border: 2px solid #ccc; border-radius: 5px;")
        self.mesaLineEdit.setObjectName("mesaLineEdit")
        self.horizontalLayout.addWidget(self.mesaLineEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("font-size: 16pt; font-weight: bold; color: #333;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.usuarioLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.usuarioLineEdit.setStyleSheet("font-size: 16pt; padding: 5px; border: 2px solid #ccc; border-radius: 5px;")
        self.usuarioLineEdit.setObjectName("usuarioLineEdit")
        self.horizontalLayout.addWidget(self.usuarioLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("QTabBar::tab {\n"
"    background: #f5f5f5;\n"
"    border: 1px solid #ddd;\n"
"    padding: 8px 20px;\n"
"    font-size: 14pt;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background: #D4AF37;\n"
"    color: white;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tabComidas = QtWidgets.QWidget()
        self.tabComidas.setObjectName("tabComidas")
        self.gridLayout = QtWidgets.QGridLayout(self.tabComidas)
        self.gridLayout.setObjectName("gridLayout")
        self.comida1Button = QtWidgets.QPushButton(self.tabComidas)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 175, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 175, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 175, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 175, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 175, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 175, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 175, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 175, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 175, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.comida1Button.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comida1Button.setFont(font)
        self.comida1Button.setStyleSheet("QPushButton {\n"
"    background-color: #D4AF37;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 15px;\n"
"    font-size: 12pt;\n"
"    min-width: 150px;\n"
"    min-height: 80px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E6C200;\n"
"}")
        self.comida1Button.setObjectName("comida1Button")
        self.gridLayout.addWidget(self.comida1Button, 0, 0, 1, 1)
        self.comida1ComboBox = QtWidgets.QComboBox(self.tabComidas)
        self.comida1ComboBox.setStyleSheet("font-size: 12pt; padding: 5px; border: 2px solid #ccc; border-radius: 5px;")
        self.comida1ComboBox.setObjectName("comida1ComboBox")
        self.comida1ComboBox.addItem("")
        self.comida1ComboBox.addItem("")
        self.comida1ComboBox.addItem("")
        self.comida1ComboBox.addItem("")
        self.comida1ComboBox.addItem("")
        self.comida1ComboBox.addItem("")
        self.gridLayout.addWidget(self.comida1ComboBox, 0, 1, 1, 1)
        self.comida2Button = QtWidgets.QPushButton(self.tabComidas)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comida2Button.setFont(font)
        self.comida2Button.setStyleSheet("QPushButton {\n"
"    background-color: #D4AF37;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 15px;\n"
"    font-size: 12pt;\n"
"    min-width: 150px;\n"
"    min-height: 80px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E6C200;\n"
"}")
        self.comida2Button.setObjectName("comida2Button")
        self.gridLayout.addWidget(self.comida2Button, 1, 0, 1, 1)
        self.comida2ComboBox = QtWidgets.QComboBox(self.tabComidas)
        self.comida2ComboBox.setStyleSheet("font-size: 12pt; padding: 5px; border: 2px solid #ccc; border-radius: 5px;")
        self.comida2ComboBox.setObjectName("comida2ComboBox")
        self.comida2ComboBox.addItem("")
        self.comida2ComboBox.addItem("")
        self.comida2ComboBox.addItem("")
        self.comida2ComboBox.addItem("")
        self.comida2ComboBox.addItem("")
        self.comida2ComboBox.addItem("")
        self.gridLayout.addWidget(self.comida2ComboBox, 1, 1, 1, 1)
        self.comida3Button = QtWidgets.QPushButton(self.tabComidas)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comida3Button.setFont(font)
        self.comida3Button.setStyleSheet("QPushButton {\n"
"    background-color: #D4AF37;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 15px;\n"
"    font-size: 12pt;\n"
"    min-width: 150px;\n"
"    min-height: 80px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E6C200;\n"
"}")
        self.comida3Button.setObjectName("comida3Button")
        self.gridLayout.addWidget(self.comida3Button, 2, 0, 1, 1)
        self.comida3ComboBox = QtWidgets.QComboBox(self.tabComidas)
        self.comida3ComboBox.setStyleSheet("font-size: 12pt; padding: 5px; border: 2px solid #ccc; border-radius: 5px;")
        self.comida3ComboBox.setObjectName("comida3ComboBox")
        self.comida3ComboBox.addItem("")
        self.comida3ComboBox.addItem("")
        self.comida3ComboBox.addItem("")
        self.comida3ComboBox.addItem("")
        self.comida3ComboBox.addItem("")
        self.comida3ComboBox.addItem("")
        self.gridLayout.addWidget(self.comida3ComboBox, 2, 1, 1, 1)
        self.comida4Button = QtWidgets.QPushButton(self.tabComidas)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comida4Button.setFont(font)
        self.comida4Button.setStyleSheet("QPushButton {\n"
"    background-color: #D4AF37;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 15px;\n"
"    font-size: 12pt;\n"
"    min-width: 150px;\n"
"    min-height: 80px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E6C200;\n"
"}")
        self.comida4Button.setObjectName("comida4Button")
        self.gridLayout.addWidget(self.comida4Button, 3, 0, 1, 1)
        self.comida4ComboBox = QtWidgets.QComboBox(self.tabComidas)
        self.comida4ComboBox.setStyleSheet("font-size: 12pt; padding: 5px; border: 2px solid #ccc; border-radius: 5px;")
        self.comida4ComboBox.setObjectName("comida4ComboBox")
        self.comida4ComboBox.addItem("")
        self.comida4ComboBox.addItem("")
        self.comida4ComboBox.addItem("")
        self.comida4ComboBox.addItem("")
        self.comida4ComboBox.addItem("")
        self.comida4ComboBox.addItem("")
        self.gridLayout.addWidget(self.comida4ComboBox, 3, 1, 1, 1)
        self.comida5Button = QtWidgets.QPushButton(self.tabComidas)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comida5Button.setFont(font)
        self.comida5Button.setStyleSheet("QPushButton {\n"
"    background-color: #D4AF37;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 15px;\n"
"    font-size: 12pt;\n"
"    min-width: 150px;\n"
"    min-height: 80px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E6C200;\n"
"}")
        self.comida5Button.setObjectName("comida5Button")
        self.gridLayout.addWidget(self.comida5Button, 4, 0, 1, 1)
        self.comida5ComboBox = QtWidgets.QComboBox(self.tabComidas)
        self.comida5ComboBox.setStyleSheet("font-size: 12pt; padding: 5px; border: 2px solid #ccc; border-radius: 5px;")
        self.comida5ComboBox.setObjectName("comida5ComboBox")
        self.comida5ComboBox.addItem("")
        self.comida5ComboBox.addItem("")
        self.comida5ComboBox.addItem("")
        self.comida5ComboBox.addItem("")
        self.comida5ComboBox.addItem("")
        self.comida5ComboBox.addItem("")
        self.gridLayout.addWidget(self.comida5ComboBox, 4, 1, 1, 1)
        self.comida6Button = QtWidgets.QPushButton(self.tabComidas)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comida6Button.setFont(font)
        self.comida6Button.setStyleSheet("QPushButton {\n"
"    background-color: #D4AF37;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 15px;\n"
"    font-size: 12pt;\n"
"    min-width: 150px;\n"
"    min-height: 80px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E6C200;\n"
"}")
        self.comida6Button.setObjectName("comida6Button")
        self.gridLayout.addWidget(self.comida6Button, 5, 0, 1, 1)
        self.comida6ComboBox = QtWidgets.QComboBox(self.tabComidas)
        self.comida6ComboBox.setStyleSheet("font-size: 12pt; padding: 5px; border: 2px solid #ccc; border-radius: 5px;")
        self.comida6ComboBox.setObjectName("comida6ComboBox")
        self.comida6ComboBox.addItem("")
        self.comida6ComboBox.addItem("")
        self.comida6ComboBox.addItem("")
        self.comida6ComboBox.addItem("")
        self.comida6ComboBox.addItem("")
        self.comida6ComboBox.addItem("")
        self.gridLayout.addWidget(self.comida6ComboBox, 5, 1, 1, 1)
        self.comida7Button = QtWidgets.QPushButton(self.tabComidas)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comida7Button.setFont(font)
        self.comida7Button.setStyleSheet("QPushButton {\n"
"    background-color: #D4AF37;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 15px;\n"
"    font-size: 12pt;\n"
"    min-width: 150px;\n"
"    min-height: 80px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E6C200;\n"
"}")
        self.comida7Button.setObjectName("comida7Button")
        self.gridLayout.addWidget(self.comida7Button, 6, 0, 1, 1)
        self.comida7ComboBox = QtWidgets.QComboBox(self.tabComidas)
        self.comida7ComboBox.setStyleSheet("font-size: 12pt; padding: 5px; border: 2px solid #ccc; border-radius: 5px;")
        self.comida7ComboBox.setObjectName("comida7ComboBox")
        self.comida7ComboBox.addItem("")
        self.comida7ComboBox.addItem("")
        self.comida7ComboBox.addItem("")
        self.comida7ComboBox.addItem("")
        self.comida7ComboBox.addItem("")
        self.comida7ComboBox.addItem("")
        self.gridLayout.addWidget(self.comida7ComboBox, 6, 1, 1, 1)
        self.comida8Button = QtWidgets.QPushButton(self.tabComidas)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comida8Button.setFont(font)
        self.comida8Button.setStyleSheet("QPushButton {\n"
"    background-color: #D4AF37;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 15px;\n"
"    font-size: 12pt;\n"
"    min-width: 150px;\n"
"    min-height: 80px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E6C200;\n"
"}")
        self.comida8Button.setObjectName("comida8Button")
        self.gridLayout.addWidget(self.comida8Button, 7, 0, 1, 1)
        self.comida8ComboBox = QtWidgets.QComboBox(self.tabComidas)
        self.comida8ComboBox.setStyleSheet("font-size: 12pt; padding: 5px; border: 2px solid #ccc; border-radius: 5px;")
        self.comida8ComboBox.setObjectName("comida8ComboBox")
        self.comida8ComboBox.addItem("")
        self.comida8ComboBox.addItem("")
        self.comida8ComboBox.addItem("")
        self.comida8ComboBox.addItem("")
        self.comida8ComboBox.addItem("")
        self.comida8ComboBox.addItem("")
        self.gridLayout.addWidget(self.comida8ComboBox, 7, 1, 1, 1)
        self.tabWidget.addTab(self.tabComidas, "")
        self.tabBebidas = QtWidgets.QWidget()
        self.tabBebidas.setObjectName("tabBebidas")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabBebidas)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bebida1Button = QtWidgets.QPushButton(self.tabBebidas)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bebida1Button.setFont(font)
        self.bebida1Button.setStyleSheet("QPushButton {\n"
"    background-color: #D4AF37;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 15px;\n"
"    font-size: 12pt;\n"
"    min-width: 150px;\n"
"    min-height: 80px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E6C200;\n"
"}")
        self.bebida1Button.setObjectName("bebida1Button")
        self.gridLayout_2.addWidget(self.bebida1Button, 0, 0, 1, 1)
        self.bebida1ComboBox = QtWidgets.QComboBox(self.tabBebidas)
        self.bebida1ComboBox.setStyleSheet("font-size: 12pt; padding: 5px; border: 2px solid #ccc; border-radius: 5px;")
        self.bebida1ComboBox.setObjectName("bebida1ComboBox")
        self.bebida1ComboBox.addItem("")
        self.bebida1ComboBox.addItem("")
        self.bebida1ComboBox.addItem("")
        self.bebida1ComboBox.addItem("")
        self.bebida1ComboBox.addItem("")
        self.bebida1ComboBox.addItem("")
        self.gridLayout_2.addWidget(self.bebida1ComboBox, 0, 1, 1, 1)
        self.bebida2Button = QtWidgets.QPushButton(self.tabBebidas)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bebida2Button.setFont(font)
        self.bebida2Button.setStyleSheet("QPushButton {\n"
"    background-color: #D4AF37;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 15px;\n"
"    font-size: 12pt;\n"
"    min-width: 150px;\n"
"    min-height: 80px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E6C200;\n"
"}")
        self.bebida2Button.setObjectName("bebida2Button")
        self.gridLayout_2.addWidget(self.bebida2Button, 1, 0, 1, 1)
        self.bebida2ComboBox = QtWidgets.QComboBox(self.tabBebidas)
        self.bebida2ComboBox.setStyleSheet("font-size: 12pt; padding: 5px; border: 2px solid #ccc; border-radius: 5px;")
        self.bebida2ComboBox.setObjectName("bebida2ComboBox")
        self.bebida2ComboBox.addItem("")
        self.bebida2ComboBox.addItem("")
        self.bebida2ComboBox.addItem("")
        self.bebida2ComboBox.addItem("")
        self.bebida2ComboBox.addItem("")
        self.bebida2ComboBox.addItem("")
        self.gridLayout_2.addWidget(self.bebida2ComboBox, 1, 1, 1, 1)
        self.bebida3Button = QtWidgets.QPushButton(self.tabBebidas)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bebida3Button.setFont(font)
        self.bebida3Button.setStyleSheet("QPushButton {\n"
"    background-color: #D4AF37;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 15px;\n"
"    font-size: 12pt;\n"
"    min-width: 150px;\n"
"    min-height: 80px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E6C200;\n"
"}")
        self.bebida3Button.setObjectName("bebida3Button")
        self.gridLayout_2.addWidget(self.bebida3Button, 2, 0, 1, 1)
        self.bebida3ComboBox = QtWidgets.QComboBox(self.tabBebidas)
        self.bebida3ComboBox.setStyleSheet("font-size: 12pt; padding: 5px; border: 2px solid #ccc; border-radius: 5px;")
        self.bebida3ComboBox.setObjectName("bebida3ComboBox")
        self.bebida3ComboBox.addItem("")
        self.bebida3ComboBox.addItem("")
        self.bebida3ComboBox.addItem("")
        self.bebida3ComboBox.addItem("")
        self.bebida3ComboBox.addItem("")
        self.bebida3ComboBox.addItem("")
        self.gridLayout_2.addWidget(self.bebida3ComboBox, 2, 1, 1, 1)
        self.bebida4Button = QtWidgets.QPushButton(self.tabBebidas)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bebida4Button.setFont(font)
        self.bebida4Button.setStyleSheet("QPushButton {\n"
"    background-color: #D4AF37;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 15px;\n"
"    font-size: 12pt;\n"
"    min-width: 150px;\n"
"    min-height: 80px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E6C200;\n"
"}")
        self.bebida4Button.setObjectName("bebida4Button")
        self.gridLayout_2.addWidget(self.bebida4Button, 3, 0, 1, 1)
        self.bebida4ComboBox = QtWidgets.QComboBox(self.tabBebidas)
        self.bebida4ComboBox.setStyleSheet("font-size: 12pt; padding: 5px; border: 2px solid #ccc; border-radius: 5px;")
        self.bebida4ComboBox.setObjectName("bebida4ComboBox")
        self.bebida4ComboBox.addItem("")
        self.bebida4ComboBox.addItem("")
        self.bebida4ComboBox.addItem("")
        self.bebida4ComboBox.addItem("")
        self.bebida4ComboBox.addItem("")
        self.bebida4ComboBox.addItem("")
        self.gridLayout_2.addWidget(self.bebida4ComboBox, 3, 1, 1, 1)
        self.bebida5Button = QtWidgets.QPushButton(self.tabBebidas)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bebida5Button.setFont(font)
        self.bebida5Button.setStyleSheet("QPushButton {\n"
"    background-color: #D4AF37;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 15px;\n"
"    font-size: 12pt;\n"
"    min-width: 150px;\n"
"    min-height: 80px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E6C200;\n"
"}")
        self.bebida5Button.setObjectName("bebida5Button")
        self.gridLayout_2.addWidget(self.bebida5Button, 4, 0, 1, 1)
        self.bebida5ComboBox = QtWidgets.QComboBox(self.tabBebidas)
        self.bebida5ComboBox.setStyleSheet("font-size: 12pt; padding: 5px; border: 2px solid #ccc; border-radius: 5px;")
        self.bebida5ComboBox.setObjectName("bebida5ComboBox")
        self.bebida5ComboBox.addItem("")
        self.bebida5ComboBox.addItem("")
        self.bebida5ComboBox.addItem("")
        self.bebida5ComboBox.addItem("")
        self.bebida5ComboBox.addItem("")
        self.bebida5ComboBox.addItem("")
        self.gridLayout_2.addWidget(self.bebida5ComboBox, 4, 1, 1, 1)
        self.bebida6Button = QtWidgets.QPushButton(self.tabBebidas)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bebida6Button.setFont(font)
        self.bebida6Button.setStyleSheet("QPushButton {\n"
"    background-color: #D4AF37;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 15px;\n"
"    font-size: 12pt;\n"
"    min-width: 150px;\n"
"    min-height: 80px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E6C200;\n"
"}")
        self.bebida6Button.setObjectName("bebida6Button")
        self.gridLayout_2.addWidget(self.bebida6Button, 5, 0, 1, 1)
        self.bebida6ComboBox = QtWidgets.QComboBox(self.tabBebidas)
        self.bebida6ComboBox.setStyleSheet("font-size: 12pt; padding: 5px; border: 2px solid #ccc; border-radius: 5px;")
        self.bebida6ComboBox.setObjectName("bebida6ComboBox")
        self.bebida6ComboBox.addItem("")
        self.bebida6ComboBox.addItem("")
        self.bebida6ComboBox.addItem("")
        self.bebida6ComboBox.addItem("")
        self.bebida6ComboBox.addItem("")
        self.bebida6ComboBox.addItem("")
        self.gridLayout_2.addWidget(self.bebida6ComboBox, 5, 1, 1, 1)
        self.bebida7Button = QtWidgets.QPushButton(self.tabBebidas)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bebida7Button.setFont(font)
        self.bebida7Button.setStyleSheet("QPushButton {\n"
"    background-color: #D4AF37;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 15px;\n"
"    font-size: 12pt;\n"
"    min-width: 150px;\n"
"    min-height: 80px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E6C200;\n"
"}")
        self.bebida7Button.setObjectName("bebida7Button")
        self.gridLayout_2.addWidget(self.bebida7Button, 6, 0, 1, 1)
        self.bebida7ComboBox = QtWidgets.QComboBox(self.tabBebidas)
        self.bebida7ComboBox.setStyleSheet("font-size: 12pt; padding: 5px; border: 2px solid #ccc; border-radius: 5px;")
        self.bebida7ComboBox.setObjectName("bebida7ComboBox")
        self.bebida7ComboBox.addItem("")
        self.bebida7ComboBox.addItem("")
        self.bebida7ComboBox.addItem("")
        self.bebida7ComboBox.addItem("")
        self.bebida7ComboBox.addItem("")
        self.bebida7ComboBox.addItem("")
        self.gridLayout_2.addWidget(self.bebida7ComboBox, 6, 1, 1, 1)
        self.bebida8Button = QtWidgets.QPushButton(self.tabBebidas)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bebida8Button.setFont(font)
        self.bebida8Button.setStyleSheet("QPushButton {\n"
"    background-color: #D4AF37;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 15px;\n"
"    font-size: 12pt;\n"
"    min-width: 150px;\n"
"    min-height: 80px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E6C200;\n"
"}")
        self.bebida8Button.setObjectName("bebida8Button")
        self.gridLayout_2.addWidget(self.bebida8Button, 7, 0, 1, 1)
        self.bebida8ComboBox = QtWidgets.QComboBox(self.tabBebidas)
        self.bebida8ComboBox.setStyleSheet("font-size: 12pt; padding: 5px; border: 2px solid #ccc; border-radius: 5px;")
        self.bebida8ComboBox.setObjectName("bebida8ComboBox")
        self.bebida8ComboBox.addItem("")
        self.bebida8ComboBox.addItem("")
        self.bebida8ComboBox.addItem("")
        self.bebida8ComboBox.addItem("")
        self.bebida8ComboBox.addItem("")
        self.bebida8ComboBox.addItem("")
        self.gridLayout_2.addWidget(self.bebida8ComboBox, 7, 1, 1, 1)
        self.tabWidget.addTab(self.tabBebidas, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.editarPedidoButton = QtWidgets.QPushButton(self.centralwidget)
        self.editarPedidoButton.setStyleSheet("QPushButton {\n"
"    background-color: #FFC107;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 15px 30px;\n"
"    font-size: 16pt;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"    min-width: 200px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FFD54F;\n"
"}")
        self.editarPedidoButton.setObjectName("editarPedidoButton")
        self.horizontalLayout_2.addWidget(self.editarPedidoButton)
        self.cerrarPedidoButton = QtWidgets.QPushButton(self.centralwidget)
        self.cerrarPedidoButton.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 15px 30px;\n"
"    font-size: 16pt;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    min-width: 200px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}")
        self.cerrarPedidoButton.setObjectName("cerrarPedidoButton")
        self.horizontalLayout_2.addWidget(self.cerrarPedidoButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema de Pedidos"))
        self.label.setText(_translate("MainWindow", "Mesa:"))
        self.mesaLineEdit.setPlaceholderText(_translate("MainWindow", "Número de mesa"))
        self.label_2.setText(_translate("MainWindow", "Mesero:"))
        self.usuarioLineEdit.setPlaceholderText(_translate("MainWindow", "Nombre del mesero"))
        self.comida1Button.setText(_translate("MainWindow", "Hamburguesa"))
        self.comida1ComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.comida1ComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.comida1ComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.comida1ComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.comida1ComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.comida1ComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.comida2Button.setText(_translate("MainWindow", "Pizza"))
        self.comida2ComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.comida2ComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.comida2ComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.comida2ComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.comida2ComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.comida2ComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.comida3Button.setText(_translate("MainWindow", "Ensalada"))
        self.comida3ComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.comida3ComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.comida3ComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.comida3ComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.comida3ComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.comida3ComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.comida4Button.setText(_translate("MainWindow", "Pasta"))
        self.comida4ComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.comida4ComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.comida4ComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.comida4ComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.comida4ComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.comida4ComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.comida5Button.setText(_translate("MainWindow", "Sopa"))
        self.comida5ComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.comida5ComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.comida5ComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.comida5ComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.comida5ComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.comida5ComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.comida6Button.setText(_translate("MainWindow", "Sandwich"))
        self.comida6ComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.comida6ComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.comida6ComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.comida6ComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.comida6ComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.comida6ComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.comida7Button.setText(_translate("MainWindow", "Tacos"))
        self.comida7ComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.comida7ComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.comida7ComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.comida7ComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.comida7ComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.comida7ComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.comida8Button.setText(_translate("MainWindow", "Pollo"))
        self.comida8ComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.comida8ComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.comida8ComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.comida8ComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.comida8ComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.comida8ComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabComidas), _translate("MainWindow", "Comidas"))
        self.bebida1Button.setText(_translate("MainWindow", "Refresco"))
        self.bebida1ComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.bebida1ComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.bebida1ComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.bebida1ComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.bebida1ComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.bebida1ComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.bebida2Button.setText(_translate("MainWindow", "Jugo"))
        self.bebida2ComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.bebida2ComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.bebida2ComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.bebida2ComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.bebida2ComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.bebida2ComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.bebida3Button.setText(_translate("MainWindow", "Cerveza"))
        self.bebida3ComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.bebida3ComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.bebida3ComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.bebida3ComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.bebida3ComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.bebida3ComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.bebida4Button.setText(_translate("MainWindow", "Agua"))
        self.bebida4ComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.bebida4ComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.bebida4ComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.bebida4ComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.bebida4ComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.bebida4ComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.bebida5Button.setText(_translate("MainWindow", "Café"))
        self.bebida5ComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.bebida5ComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.bebida5ComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.bebida5ComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.bebida5ComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.bebida5ComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.bebida6Button.setText(_translate("MainWindow", "Té"))
        self.bebida6ComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.bebida6ComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.bebida6ComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.bebida6ComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.bebida6ComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.bebida6ComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.bebida7Button.setText(_translate("MainWindow", "Vino"))
        self.bebida7ComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.bebida7ComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.bebida7ComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.bebida7ComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.bebida7ComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.bebida7ComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.bebida8Button.setText(_translate("MainWindow", "Licuado"))
        self.bebida8ComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.bebida8ComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.bebida8ComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.bebida8ComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.bebida8ComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.bebida8ComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBebidas), _translate("MainWindow", "Bebidas"))
        self.editarPedidoButton.setText(_translate("MainWindow", "Editar Pedido"))
        self.cerrarPedidoButton.setText(_translate("MainWindow", "Cerrar Pedido"))
