# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\POO\PROYECTOS\Proyectoe\Ui\u_meseros.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(690, 569)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(30, 80, 631, 461))
        self.widget.setStyleSheet("background-image: url(:/mesas/gris.jpeg);")
        self.widget.setObjectName("widget")
        self.pushMESAM4 = QtWidgets.QPushButton(self.widget)
        self.pushMESAM4.setGeometry(QtCore.QRect(50, 190, 171, 111))
        self.pushMESAM4.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushMESAM4.setObjectName("pushMESAM4")
        self.pushMESAM1 = QtWidgets.QPushButton(self.widget)
        self.pushMESAM1.setGeometry(QtCore.QRect(50, 50, 171, 111))
        self.pushMESAM1.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-color: rgb(0, 255, 0);")
        self.pushMESAM1.setObjectName("pushMESAM1")
        self.pushMESAM2 = QtWidgets.QPushButton(self.widget)
        self.pushMESAM2.setGeometry(QtCore.QRect(230, 50, 171, 111))
        self.pushMESAM2.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushMESAM2.setObjectName("pushMESAM2")
        self.pushMESAM5 = QtWidgets.QPushButton(self.widget)
        self.pushMESAM5.setGeometry(QtCore.QRect(230, 190, 171, 111))
        self.pushMESAM5.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushMESAM5.setObjectName("pushMESAM5")
        self.pushMESAM6 = QtWidgets.QPushButton(self.widget)
        self.pushMESAM6.setGeometry(QtCore.QRect(410, 190, 171, 111))
        self.pushMESAM6.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushMESAM6.setObjectName("pushMESAM6")
        self.pushMESAM3 = QtWidgets.QPushButton(self.widget)
        self.pushMESAM3.setGeometry(QtCore.QRect(410, 50, 171, 111))
        self.pushMESAM3.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushMESAM3.setObjectName("pushMESAM3")
        self.salirmeseros = QtWidgets.QPushButton(self.widget)
        self.salirmeseros.setGeometry(QtCore.QRect(480, 400, 93, 28))
        self.salirmeseros.setObjectName("salirmeseros")
        self.pushMESAM4.raise_()
        self.pushMESAM2.raise_()
        self.pushMESAM5.raise_()
        self.pushMESAM6.raise_()
        self.pushMESAM3.raise_()
        self.salirmeseros.raise_()
        self.pushMESAM1.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushMESAM4.setText(_translate("Dialog", "MESA 4"))
        self.pushMESAM1.setText(_translate("Dialog", "MESA 1"))
        self.pushMESAM2.setText(_translate("Dialog", "MESA 2"))
        self.pushMESAM5.setText(_translate("Dialog", "MESA 5"))
        self.pushMESAM6.setText(_translate("Dialog", "MESA 6"))
        self.pushMESAM3.setText(_translate("Dialog", "MESA 3"))
        self.salirmeseros.setText(_translate("Dialog", "salir"))
import fr_rc
